openapi: "3.0.0"

info:
  title: Art classifier API
  description: API for the art classifier
  version: "0.1"

servers:
  - url: /api

paths:
  /query:
    post:
      operationId: "classifier.api.query"
      description: Query the classifier
      requestBody:
        description: Image to test with
        required: true
        content:
          image/*:
            schema:
              type: string
              format: binary
      responses:
        200:
          description: "Succesful query operation"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
